[package]
name = "dtproton"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
calamine = "0.26"
regex = "1"
umya-spreadsheet = "2"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"
